package com.lmig.ci.policy.services.rules.coverages 

	import com.lmig.ci.policy.services.codemonkey.vo.defulter.coverages.*; 
	import com.lmig.ci.policy.services.codemonkey.vo.*; 

	rule "BPP Is Higher ClassCode" when 
		$crit : Criteria( classCode in ("002816") ) 
	then 
		Coverage cov = new Coverage();
		cov.setName("BPP");
		cov.setSelected("Y");
		cov.setValue("200000");
		cov.setType("S");
		cov.setPremiumAmount("95.95");
		insertLogical( cov ); 
	end 

	rule "BPP Is Happy Path" when 
		$crit : Criteria( classCode not in ("002816") ) 
	then 
		Coverage cov = new Coverage();
		cov.setName("BPP");
		cov.setSelected("Y");
		cov.setValue("150000");
		cov.setType("S");
		cov.setPremiumAmount("90.22");
		insertLogical( cov ); 
	end 
