package com.lmig.ci.policy.services.rules.coverages 

	import com.lmig.ci.policy.services.codemonkey.vo.defulter.coverages.*; 
	import com.lmig.ci.policy.services.codemonkey.vo.*; 

	rule IsAAAforIN when 
		$crit : Criteria( state == "IN" ) 
	then 
		Coverage cov = new Coverage();
		cov.setName("AAA");
		cov.setValue("1234");
		insertLogical( cov ); 
	end 

	rule IsAAAnotIN when 
		$crit : Criteria( state != "IN" ) 
	then 
		Coverage cov = new Coverage();
		cov.setName("AAA");
		cov.setValue("1212");
		insertLogical( cov ); 
	end 
