package com.lmig.ci.policy.services.rules.coverages 

	import com.lmig.ci.policy.services.codemonkey.vo.defulter.coverages.*; 
	import com.lmig.ci.policy.services.codemonkey.vo.*; 

	rule "HiredAutoPD Is Happy Path" when 
	then 
		Coverage cov = new Coverage();
		cov.setName("Hired Auto Physical Damage");
		cov.setSelected("N");
		cov.setType("O");
		cov.setPremiumAmount("61.00");
		insertLogical( cov ); 
	end 
